{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kube-tetris.fullname" . }}
  labels:
    {{- include "kube-tetris.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
