server.port=8080
spring.application.name=kube-tetris-api

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=always

logging.level.org.springframework=WARN
logging.level.com.kubetetris=INFO
